### ISSUE TITLE
How to enable per-task mode

### ISSUE THREAD

**Issue by boz25** [heechul/memguard#9]
It seems memguard does not support allocate memory bandwidth by task.
When run the following commond:

> echo  taskprio 1 > /sys/kernel/debug/memguard/control

memgurad Ignored the command,as the source code show:
```
static ssize_t memguard_control_write(struct file *filp,
				    const char __user *ubuf,
				    size_t cnt, loff_t *ppos)
{
	char buf[BUF_SIZE];
	char *p = buf;
	if (copy_from_user(&buf, ubuf, (cnt > BUF_SIZE) ? BUF_SIZE: cnt) != 0)
		return 0;

	if (!strncmp(p, "exclusive ", 10))
		sscanf(p+10, "%d", &g_use_exclusive);
	else
		pr_info("ERROR: %s\n", p);
	return cnt;
}
```
How can I allocate memory bandwidth for tasks

**Comment by wali-ku** [comment]
@boz25 , memguard no longer supports the per-task mode as you have observed. However, there are other alternatives that you can consider for this:

[BWLOCK++](https://github.com/wali-ku/BWLOCK-GPU): The [kernel module](https://github.com/wali-ku/BWLOCK-GPU/tree/master/kernel_module) in BWLOCK++ is based on MemGuard and the code-base is very similar as well. BWLOCK++ allows per-task memory bandwidth assignment with the help of a [system-call](https://github.com/wali-ku/BWLOCK-GPU/blob/a4b57690eb1703019017db54e5106987c04d2ac0/kernel/miscs/bwlock%2B%2B.patch#L74). The system-call allows a task to enable / disable memory bandwidth regulation for co-running best-effort tasks. When used with BWLOCK++ [kernel-interface](https://github.com/wali-ku/BWLOCK-GPU/blob/a4b57690eb1703019017db54e5106987c04d2ac0/scripts/individual_figures/fig8-threshold.sh#L16) for changing the memory-usage threshold value, it can be used for per-task memory bandwidth regulation.

[RT-Gang](https://github.com/CSL-KU/RT-Gang/tree/devel): This is our latest work and it provides a versatile kernel interface for memory bandwidth regulation. The system-call in RT-Gang allows a more direct way to do per-task memory regulation since the memory bandwidth budget is declared explicitly by the caller via the [system-call](https://github.com/CSL-KU/RT-Gang/blob/ea2d24b9f631b210389b715c77bb84200f63d3b3/rtgang_v4.4.patch#L218). By default, it allows setting memory read and memory write budgets for the calling task independently. Furthermore, it allows creation of more regulation events in addition to the default ones via the kernel interface.

**Comment by boz25** [comment]
@wali-ku  Thank you very much. It's very helpful. I'll try out these new tools.
